version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./pratchat.db:/app/pratchat.db
    restart: unless-stopped

  frontend:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3000:5173"
    volumes:
      - ./client:/app
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - backend
    restart: unless-stopped
